name: Update GitHub Activity
on:
  schedule:
    - cron: "0 * * * *" # Updates every hour
  workflow_dispatch:
jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "Updating recent GitHub activity"
